[project]
name = "def-main"
version = "0.11.1"
description = "ğŸ—£ A decorator for main ğŸ—£"
authors = [{ name = "Tom Ritchford", email = "tom@swirly.com" }]
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
classifiers = ["Programming Language :: Python :: 3", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13", "Programming Language :: Python :: 3.14"]
dependencies = ["xmod>=1.3.2,<2"]

[tool.doks]
auto = true

[tool.coverage]

[tool.ruff.format]
quote-style = "single"
[dependency-groups]
dev = [
    "coverage>=6.5.0,<7",
    "pytest>=7.2.0,<8",
    "pyupgrade>=3.21.2",
    "ruff>=0.14.14",
    "ty>=0.0.14",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

